spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  application:
    name: ScanLinkAPI
  mongodb:
    uri: ${MONGODB_URI}
    database: scanlink


cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

  logging:
    level:
      org.springframework.web: INFO

scanlink:
  storage:
    url_folder_server: "C:/Users/ADMIN/Downloads/test"
    url_folder_cloudinary: "scanlink/uploads"
