server:
  port: 8080

spring:
  mongodb:
    uri: mongodb+srv://thietvo02_db_user:keenetic@scanlink.pkullw8.mongodb.net/scanlink_db?retryWrites=true&w=majority&appName=ScanLink

cloudinary:
  cloud-name: dusramtwo
  api-key: 498537943778555
  api-secret: h5HgUOZhWWdwWfcdUNWSFlaL_FU

logging:
  level:
    org.springframework.web: INFO
